### PR TITLE
massively improved search

### PR DESCRIPTION
**Pull request by tjtemple**
image
- Added search and clear buttons
- Separated route & train number searches, can now search for both as well
- Added route dropdown
- Searching nothing returns all trains
- Selected trains sort by number

Refactored a LOT of the search code to be a bit more readable (hopefully), if possible I think we should probably try to keep all that search code out of the App.js but I had way too many issues attempting that

### CODE REVIEW

**Review by wSimsT — APPROVED** [review]
Looks good to me

**Review by ahgoldmeer — APPROVED** [review]
Looks great! Excited to see how this all looks together in main!

**Review by nicholasrehac — APPROVED** [review]
Looks good!

**Review by ldups — APPROVED** [review]
Looks good!

**Pull request merged**
