### PR TITLE
Show all routes on map

### PR DESCRIPTION
**Pull request by ldups**
Displays all routes on the map with different colors:
image

When a route is selected by the user, the specific route is highlighted on the map in the same color.

It would be cool to filter the routes here to match the ones available through the Amtrak API, then show the same colors in the routes dropdown as on the map, but I didn't feel like doing that at the moment.

Also, I renamed the Map component because I wanted to use a JavaScript Map.

### CODE REVIEW

**Review by molly-pop — APPROVED** [review]
Pretty! I didn't know there was a way to do a script map so awesome job!

**Review by tjtemple — APPROVED** [review]
looks awesome! I'm a little offset by the route changing instantly while the trains wait for search, but we can maybe resolve that on a future commit. We might also want to hide the raw geojson
image

**Comment by tjtemple** [comment]
(for some reason colormap wasn't added to package.json so I fixed that quickly so it actually runs)

**Comment by ldups** [comment]
> (for some reason colormap wasn't added to package.json so I fixed that quickly so it actually runs)

whoops thanks for fixing this @tjtemple !

Also for the routes on the map updating, my thought was that maybe a user before searching wants to see where the route they are searching for is, without necessarily seeing the trains on it, but we can definitely talk about it

**Review by wSimsT — APPROVED** [review]
Looks neat, thanks

**Pull request merged**
