### PR TITLE
Styling fixes

### PR DESCRIPTION
**Pull request by ldups**
This PR fixes some minor styling bugs:
- favorites dropdown for long routes extending outside of search component
- search buttons extending below the bottom of the component
- unnecessary scroll bars on search

I also cleaned up some duplicate or unused CSS style rules, and removed comments such as this one 🙂:

image

### CODE REVIEW

**Review by molly-pop — APPROVED** [review]
Looks good! Might need to add back in the box shadow for the Map container if it's not anywhere else

**Comment by ldups** [comment]
> Looks good! Might need to add back in the box shadow for the Map container if it's not anywhere else 

There was an almost exactly duplicated style set for map-container in another file, so I just deleted one here and kept the other.

**Review by tjtemple — APPROVED** [review]
thanks for simplifying things!

**Review by wSimsT — APPROVED** [review]
Thank you!

**Pull request merged**
