### PR TITLE
Refactor App.js

### PR DESCRIPTION
**Pull request by ldups**
Moved search function into separate file (could separate it into multiple functions as well but felt like it wasn't too bad), and fixed a bunch of warnings (incorrect array map usage, no keys on React children). Console should be a lot cleaner now!

Also: I moved the search state down from App.js to Search.js. Since we are only updating the displayed trains upon form submission now, we don't need to update the App component anytime anything changes in the form. This simplifies both components and will reduce the amount of re-renders.

Also, not really sure what was going on with the Search component after the last update- it seemed like sort of a half controlled/ half uncontrolled component, so this also takes care of that. And removes this function header 😭:

image

### CODE REVIEW

**Review by wSimsT — APPROVED** [review]
Looks good, thanks.

**Review by molly-pop — APPROVED** [review]
Looks good Louise!

**Review by ahgoldmeer — APPROVED** [review]
Greatly needed. Thanks.

**Review by nicholasrehac — APPROVED** [review]
Looks nice!

**Pull request merged**
