### PR TITLE
Leaflet Amtrak Map

### PR DESCRIPTION
**Pull request by molly-pop**
Added GeoJSON layers to the Leaflet map such that you can see Amtrak rail lines and stations. 
Updated the styling on the webapp so containers are laid out appropriately and are responsive to window resizing 

layout

### CODE REVIEW

**Review by ldups — APPROVED** [review]
Looks so good, great job Molly!!

**Review by ahgoldmeer — APPROVED** [review]
Looks great! Really well done.

**Review by tjtemple — APPROVED** [review]
looks great

**Review by wSimsT — APPROVED** [review]
Looks good to me

**Review by nicholasrehac — APPROVED** [review]
Looks very nice!

**Pull request merged**
