### PR TITLE
Local cache

### PR DESCRIPTION
**Pull request by wSimsT**
It currently saves the searchKey into the localCache with the use of an extra button which will add it to the "favorites" cache

### CODE REVIEW

**Review by tjtemple — APPROVED** [review]
looks good so far. how do you view the data from the cache?

**Review by molly-pop — APPROVED** [review]
Good work Will!

**Review by ahgoldmeer — APPROVED** [review]
Nice! Well done.

**Review by ldups — APPROVED** [review]
Excited to see this in action!

**Pull request merged**
