### PR TITLE
Backend getStations feature + automatic deployment

### PR DESCRIPTION
**Pull request by nicholasrehac**
- station data now available from api
- support automatic cloudflare deployment
- localhost dev backend added, used by default
- dependency added, remember to run "npm i"

### CODE REVIEW

**Comment by ldups** [comment]
getting failed to fetch errors on all of the api stuff with this, not sure if it's just a me thing 😃

**Review by ldups — APPROVED** [review]
Working for me now, thanks for fixing this!

**Review by molly-pop — COMMENTED** [review]
Looks good to me!

**Review by tjtemple — APPROVED** [review]
great stuff

**Pull request merged**
