### PR TITLE
Changed train list to train table

### PR DESCRIPTION
**Pull request by ahgoldmeer**
Updated TrainList.js to produce a table that includes Train Number, Line Name, From, To, and Status.

Table items still link to popups, with more details within. 

The Train Number is meant to be displayed as white in the header row, but I've been unable to make it do that so far.

### CODE REVIEW

**Review by tjtemple — APPROVED** [review]
looks slick, great work

**Review by ldups — APPROVED** [review]
This looks amazing, great job Amitai!! Sorry for my styling scope mistake lol

**Review by wSimsT — APPROVED** [review]
Looks good to me

**Review by nicholasrehac — APPROVED** [review]
Looks clean!

**Pull request merged**
